name: commit-write-on-readme

on:
  push:
    branches: 
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit-write-on-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
          architecture: 'x64'
      - name: Run Python
        working-directory: ./.github-actions-scripts/write_commit_message_to_readme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python write_cm_2_readme.py
